### ISSUE TITLE
디지털포용포럼 디지털격차해소분과 토론방

### ISSUE THREAD

**Issue by s910374** [s910374/-#4]

**Comment by s910374** [comment]
□ 운영목적
 ㅇ 디지털 불평등 해소 관련 학계·현장리더로 구성된 전문가 그룹 운영을 통해 제도개선, 기술개발, 아젠다 발굴 등 협력적 정책추진 도모

□ 구성원
1 | 김상옥 | 회장 | 운숙미술회 | 운영위원회
2 | 김종배 | 교수 | 연세대학교 작업치료학과
3 | 노석준* | 교수 | 성신여자대학교 사범대학
4 | 최문정 | 교수 | KAIST 정책대학원
5 | 김지은 | 교수 | 한양대 기술경영대학원 | 학계
6 | 문현주 | 교수 | 충북대학교
7 | 인동준 | 상임이사 | 공동체 IT사회적협동조합 | 민간
8 | 정부만 | 본부장 | NIA 디지털포용본부 | 공공
9 | 박종선 | 팀장 | NIA 디지털격차해소팀
10 | 유재공 | 선임 | NIA 디지털격차해소팀

   * 참석자 호선을 통해 디지털격차해소 분과장은 노석준 교수로 선정

**Comment by s910374** [comment]
착수회의에서 제기된 이슈들 

1. 새로운 디지털 불평등 해소를 위한 중장기 방안 필요

2. 수요조사 등 현장 의견을 반영한 우선수행 과제 도출 필요

3. 민관협력 네트워크 구축 협의

4. 기타(디지털격차해소분과 운영 방식 및 추진 과제에 대한 제언)

**Comment by s910374** [comment]
o (정기회의) 격월 개최(7월, 9월, 11월)
     - 정기회의 개최 시 분과 전문가별 관심 분야 및 이슈 발표
     - 7월, 9월, 11월에 관심분야에 대한 소규모 세미나를 일관적 주제로 개최
      (주제 예시 : 디지털 불평등 중장기 방안, 인력양성, 
디지털 포용과 대기업 역할 및 중소기업 동참 등 민관협력 네트워크, 디지털포용 서비스 모델 발굴, AI/데이터 이용 격차 등)

**Comment by s910374** [comment]
o (수시회의) 정보접근성 정책연구 및 이슈 대응 작업반 회의 개최
- 웹 접근성 국가표준 개정 작업반

**Comment by s910374** [comment]
o (전체 세미나) 디지털 포용 포럼 3개 분과 통합 세미나 개최(11월 예정)

**Comment by s910374** [comment]
o (추가 추진과제) 정보취약계층 대상 수요조사 실시하여 우선 수행과제 도출

**Comment by s910374** [comment]
(토의 주제) 디지털 포용 관련 대기업 참여 시 역할 및 함께 할 수 있는 분야 및 활동들

**Comment by s910374** [comment]
> (토의 주제) 디지털 포용 관련 대기업 참여 시 역할 및 함께 할 수 있는 분야 및 활동들

**Comment by szroh** [comment]
디지털격차해소분과의 향후 로드맵을 성정하기 위한 분과회의를 6월 중순경에 개최하기로 하였는데, 일정을 조율해야 할 것 같습니다. 사무국의 어떤 분께 도움을 요청해야 하나요?

**Comment by s910374** [comment]
안녕하세요. 노석준 교수님

NIA 송재일입니다.

*1. 디지털포용포럼 디지털격차해소분과 및 웹 접근성 국가표준 개정 작업반 행정지원 관련 *

제가 도와드려야 하는데 지금 시급하게 해야 하는 일이
좀 밀려있어서요.

그래서, 이 일도 있고 웹 접근성 국가표준 개정반 운영도 있고 해서
학생 중에 행정을 아르바이트로 도와줄 수 있으면 제가 전문가 자문비로 처리하고 일에 좀 도움을 받을 수 있을 지 문의를 드립니다.

또한,

*2. 2019 유니버설디자인학회 춘계학술대회 참석확인서 및 자료집 부탁드림*

2019 유니버설디자인학회 춘계학술대회 참석확인서를 받지 못 해서
교육 결과보고가 너무 지체되고 있어서 제가 참석확인서 양식을 보내니 서명해서 보내주시면 감사하겠습니다.

학술대회 자료집도 주소 : *서울특별시 중구 청계천로 14 (04520) 로 착불 보내주시면 감사하겠습니다.]*

*편안한 주말 시간 되세요.*

*010-6775-5769*

2019년 6월 13일 (목) 오전 11:33, szroh <notifications@github.com>님이 작성:
